### ISSUE TITLE
How to differentiate scoring for a word that has a letter induced by us!!!!

### ISSUE THREAD

**Issue by akshchugh** [apoorvumang/Scrabble#10]

**Comment by apoorvumang** [comment]
When creating combinations, replace space with a capital letter instead of small letter.

Then you can ignore capital letters while scoring but convert to lower case when searching in hashmap

**Comment by radhikakhetan** [comment]
hey m getin a bit confused...s scoring being done again ??

**Comment by akshchugh** [comment]
seems like there is some redundancy here!!!

**Comment by radhikakhetan** [comment]
yea

**Comment by apoorvumang** [comment]
Team 1 would have a function that calculates score given a word. It can do a lookup or calculate on the fly or whatever. 

Team 2 will create a list of possible combinations. This should include combinations using blank tile, replacing them with capital letters

Team 3 will create a filter that given a list of combinations filters according to a constraint.

Here is the workflow. Everybody will contribute to it I think:
1. Construct anagram dictionary
2. Get input rack and constraint.
3. Use rack to make all combinations
4. For each combination
   
   ```
    a. score = getScore(combination)
   
    b. if in hashmap(combination), get all anagrams and store in Map<Integer, String> as score, word
   ```
5. Apply constraints to this output, then give output
