### ISSUE TITLE
Calculate score of a combination

### ISSUE THREAD

**Issue by apoorvumang** [apoorvumang/Scrabble#6]
This should take into account the presence of blank tile. Communicate with Bhavya as to how it will be done.

**Comment by apoorvumang** [comment]
Check your calculateScore implementation, it should take String word as input not int word

**Comment by apoorvumang** [comment]
Please pull the latest code and fix this function

**Comment by akshchugh** [comment]
Guys this is completed :)

**Comment by dineshchhabra** [comment]
I am changing calculateScore function

**Comment by dineshchhabra** [comment]
We don't need calculateScore() and calculateKey() in ScrabbleHelper class. I  moved these to  AnagramListStructure class.
